let g:go_code_completion_enabled = 0
let g:go_diagnostics_level = 0
let g:go_fold_enable = []
let g:gotests_bin = $GOPATH . '/bin/gotests'
let g:go_alternate_mode = "vsplit"
"let g:go_term_mode = "vsplit"
let g:go_term_enabled = 1
let g:go_term_reuse = 1
let g:go_jump_to_error = 0
let g:go_term_close_on_exit = 0
