vim.keymap.set("n", "<F5>", function()
	require("dap").continue()
end, { desc = "debug continue" })
vim.keymap.set("n", "<F10>", function()
	require("dap").step_over()
end, { desc = "debug step over" })
vim.keymap.set("n", "<F11>", function()
	require("dap").step_into()
end, { desc = "debug step into" })
vim.keymap.set("n", "<F12>", function()
	require("dap").step_out()
end, { desc = "debug step out" })
vim.keymap.set("n", "<Leader>b", function()
	require("dap").toggle_breakpoint()
end, { desc = "debug toggle breakpoint" })
